// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/qmk/qmk_firmware/keyboards/tzarc/djinn/graphics/djinn-rgb-right.png --output /home/qmk/qmk_firmware/keyboards/tzarc/djinn/graphics --format mono16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_djinn_rgb_right_length;
extern const uint8_t  gfx_djinn_rgb_right[3580];
