// Copyright 2026 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/disciple153/Documents/qmk_firmware/keyboards/tzarc/djinn/graphics/icons/icons8-mute-50.png --output /home/disciple153/Documents/qmk_firmware/keyboards/tzarc/djinn/graphics/icons --format mono4 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_icons8_mute_50_length;
extern const uint8_t  gfx_icons8_mute_50[370];
